# 图表标题与内容解析匹配挑战赛配置文件

# 数据配置
data:
  data_dir: "data"  # 数据目录
  train_file: "train.csv"  # 训练数据文件
  test_file: "test.csv"  # 测试数据文件
  sample_submit_file: "sample_submit.csv"  # 样例提交文件
  image_dir: "images"  # 图像目录
  
# 图像处理配置
image:
  model_name: "resnet50"  # 图像特征提取模型
  feature_dim: 512  # 特征维度
  pretrained: true  # 是否使用预训练模型
  image_size: [224, 224]  # 图像尺寸
  normalize_mean: [0.485, 0.456, 0.406]  # 归一化均值
  normalize_std: [0.229, 0.224, 0.225]  # 归一化标准差
  augmentation:
    enabled: true  # 是否启用数据增强
    rotation: 10  # 旋转角度
    brightness: 0.2  # 亮度变化
    contrast: 0.2  # 对比度变化
    saturation: 0.2  # 饱和度变化
    hue: 0.1  # 色调变化
    horizontal_flip: 0.5  # 水平翻转概率
    
# 文本处理配置
text:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"  # 文本特征提取模型
  feature_dim: 384  # 特征维度
  max_length: 128  # 最大文本长度
  tokenizer_config:
    padding: "max_length"  # 填充策略
    truncation: true  # 是否截断
    return_tensors: "pt"  # 返回张量类型
    
# 相似度计算配置
similarity:
  method: "cosine"  # 相似度计算方法: cosine, euclidean, dot, learned
  feature_dim: 512  # 特征维度
  temperature: 0.07  # 温度参数
  learned_config:  # 学习相似度配置
    hidden_dims: [512, 256, 128]  # 隐藏层维度
    dropout: 0.1  # Dropout率
    activation: "relu"  # 激活函数
    
# 训练配置
training:
  epochs: 50  # 训练轮数
  batch_size: 32  # 批次大小
  learning_rate: 1e-4  # 学习率
  weight_decay: 1e-5  # 权重衰减
  val_split: 0.2  # 验证集比例
  early_stopping:
    enabled: true  # 是否启用早停
    patience: 10  # 早停耐心值
    min_delta: 1e-4  # 最小改进阈值
  scheduler:
    type: "cosine"  # 学习率调度器类型
    warmup_epochs: 5  # 预热轮数
    min_lr: 1e-6  # 最小学习率
  optimizer:
    type: "adamw"  # 优化器类型
    betas: [0.9, 0.999]  # Adam参数
    eps: 1e-8  # 数值稳定性参数
  loss:
    type: "contrastive"  # 损失函数类型
    margin: 0.5  # 对比损失边界
    temperature: 0.07  # 温度参数
  max_checkpoints: 5  # 最大检查点数量
  
# 预测配置
prediction:
  batch_size: 64  # 预测批次大小
  top_k: 5  # Top-K预测
  confidence_threshold: 0.5  # 置信度阈值
  ensemble:
    enabled: false  # 是否启用集成
    methods: ["mean", "max"]  # 集成方法
  tta:
    enabled: false  # 是否启用测试时增强
    num_augmentations: 5  # 增强次数
    
# 系统配置
system:
  device: "auto"  # 计算设备: cpu, cuda, auto
  num_workers: 4  # 数据加载器工作进程数
  pin_memory: true  # 是否固定内存
  mixed_precision: true  # 是否使用混合精度
  output_dir: "outputs"  # 输出目录
  log_level: "INFO"  # 日志级别
  seed: 42  # 随机种子
  
# 评估配置
evaluation:
  metrics: ["accuracy", "top_k_accuracy", "mean_rank", "mrr", "ndcg"]  # 评估指标
  top_k_list: [1, 3, 5, 10]  # Top-K列表
  save_predictions: true  # 是否保存预测结果
  save_features: false  # 是否保存特征
  
# 可视化配置
visualization:
  enabled: true  # 是否启用可视化
  save_plots: true  # 是否保存图表
  plot_training_history: true  # 是否绘制训练历史
  plot_confusion_matrix: true  # 是否绘制混淆矩阵
  plot_similarity_distribution: true  # 是否绘制相似度分布
  plot_feature_tsne: false  # 是否绘制特征t-SNE
  interactive_dashboard: false  # 是否创建交互式仪表板